myKey: value1
server:
  port: 9090
  reactive:
    session:
      cookie:
        domain: ymlTestvalue

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testdb?characterEncoding=utf8&useSSL=false
    username: root
    password: ''

string:
  str1: Hello \n Spring Boot.
  str2: 'Hello \n Spring Boot.'
  str3: "Hello \n Spring Boot."

student:
  id: 1
  name: Java
  age: 18
  dbtypes:
    - mysql
    - sqlserver
    - db2
  maptypes:
    k1: kk1
    k2: kk2
    k3: kk3